# -*- coding: utf-8 -*-
"""breast-cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lPGKG8CxjaJuW4o26JLRgj04bGpSUyP9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

df = pd.read_csv("breast-cancer.csv")

df.head()

df.shape

df.info()

df.isnull().sum()

df = df.drop("id", axis=1)

df["diagnosis"] = df["diagnosis"].map({"M": 1, "B": 0})

X = df.drop("diagnosis", axis=1)
y = df["diagnosis"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_validate

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(random_state=42))
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== Logistic Regression =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

from sklearn.tree import DecisionTreeClassifier

pipe = Pipeline([
    ("model", DecisionTreeClassifier(random_state=42))
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== Decision Tree =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

from sklearn.ensemble import RandomForestClassifier

pipe = Pipeline([
    ("model", RandomForestClassifier(random_state=42))
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== Random Forest =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

from sklearn.svm import SVC

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", SVC())
])

scores = cross_validate(
    pipe,
    X_train,
    y_train,
    cv=5,
    scoring=["accuracy","precision","recall","f1"]
)

print("===== SVM =====")

print("\nAccuracy")
for i, score in enumerate(scores["test_accuracy"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_accuracy"].mean())

print("\nPrecision")
for i, score in enumerate(scores["test_precision"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_precision"].mean())

print("\nRecall")
for i, score in enumerate(scores["test_recall"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_recall"].mean())

print("\nF1 Score")
for i, score in enumerate(scores["test_f1"],1):
    print(f"Fold {i}: {score:.4f}")
print("Average:", scores["test_f1"].mean())

